### PR TITLE
Tweak to the CSS for the nicklist

### PR DESCRIPTION
**Pull request by graymalkin**
This removes the funny empty space at the bottom of the nick list when it is scrollable.

### CODE REVIEW

**Comment by lorenzhs** [comment]
It kinda removes a bit too much space, don't you think? The last nick ends flush with the bottom of the page. There should be at least a couple of pixels of space there imho

**Comment by graymalkin** [comment]
You're quite right, I've modified the padding at the bottom to match, so it now looks a lot better.

**Comment by lorenzhs** [comment]
I've played around with the values a bit and I think `padding-bottom: 44px` looks better and also matches the effective spacing at the top (I'm unsure how exactly this adds up, but when I hover over the first nick and observe the amount of space to the top and do the same with the last one, 44px works best for me). What do you think?

**Comment by graymalkin** [comment]
Yeah looks good to me! Much nicer than the text touching the bottom of the frame.

**Comment by lorenzhs** [comment]
Thanks, I fixed it up and merged it :)

**Pull request merged**
