### PR TITLE
Don't jump to hidden buffers with Alt-A

### PR DESCRIPTION
**Pull request by lorenzhs**
See #998

### CODE REVIEW

**Comment by JulienPalard** [comment]
Tried it for a few hours, it works as expected, thanks a lot for this fix!

**Comment by lorenzhs** [comment]
Cool, thank you!

**Comment by JulienPalard** [comment]
13 days using this PR, it works like a charm, I think this can be merged.

**Comment by lorenzhs** [comment]
Thanks, merged.

**Comment by JulienPalard** [comment]
Thank you!

**Pull request merged**
