### PR TITLE
Added ability to filter out messages (joins/parts/quits/modes)

### PR DESCRIPTION
**Pull request by chetan**
Makes for cleaner display, particularly on mobile

### CODE REVIEW

**Comment by Vaesper** [comment]
Why not use something like smart filter in weechat?

**Comment by chetan** [comment]
I'm actually not super familiar with weechat, mostly just using it via glowing bear, but I really only want to enable this filtering on mobile. Other sessions should be unfiltered. Can I do that with smart filters?

**Comment by Vaesper** [comment]
I don't think so, no. There is no way to enable/disable smart filters through GB right now, otherwise that would work.

**Comment by lorenzhs** [comment]
I think we should investigate whether there's a way to show/hide filtered lines dynamically in Glowing Bear. That should make smart filter viable for more people.

**Comment by lorenzhs** [comment]
I'm closing this because it's a bit too nice. Ideally this should be possible in CSS (maybe we could add the classes to the `tbody` object?) but I don't think it should be a setting. Most people will prefer smart filter anyway

**Pull request closed without merging**
