### PR TITLE
convert app to be built using webpack

### PR DESCRIPTION
**Pull request by yeiniel**
this is the first step on the roadmap to upgrade to the new version of the angular framework. It contributes to issue #1078 

the following changes are included:

 - add webpack to bundle app code
 - transform most of the javascript files into modules
 - upgrade travis to stop using a deprecated ubuntu image
 - upgrade karma to stop using a deprecated browser
 - remove bower and moved bower dependencies to npm

### CODE REVIEW

**Comment by lorenzhs** [comment]
Cool, thanks! Unfortunately I'm a bit unqualified to review this, I've never used webpack and know absolutely nothing about it. It'd be great if someone else could have a look.

Am I correct though that this makes webpack a build step? I always liked that there was no build step involved in hosting glowing bear, you could simply clone the repo, modify a file, and reload the page in your browser to test it. I kinda liked that. But it seems that web development just doesn't work like that any more.

**Comment by cormier** [comment]
Hi @yeiniel, thanks for your work ! This looks great. I don't have as much time as I would like this week but I will give it a look and give you feedback as soon as possible.

**Comment by yeiniel** [comment]
> Cool, thanks! Unfortunately I'm a bit unqualified to review this, I've never used webpack and know absolutely nothing about it. It'd be great if someone else could have a look.
> 
> Am I correct though that this makes webpack a build step? I always liked that there was no build step involved in hosting glowing bear, you could simply clone the repo, modify a file, and reload the page in your browser to test it. I kinda liked that. But it seems that web development just doesn't work like that any more.

Hi @lorenzhs , yes you are right, it makes webpack the build step.

**Comment by yeiniel** [comment]
`Am I correct though that this makes webpack a build step?`
Yes, that's the case. In the future during the upgrade we will need the legacy code to coexist with the new one and both to be packed together. Therefore doing the packing before helps on that process. Additionally we will need to split the code into smaller chunks to comply with angular style guide (one file per component or service rule) and easy the conversion to typescript. Without the packing having so many javascript modules becomes something ugly.

**Comment by yeiniel** [comment]
Sorry I was trying to comment from my phone and closed the pr by mistake, I re opened it again

**Comment by yeiniel** [comment]
>  I always liked that there was no build step involved in hosting glowing bear, you could simply clone the repo, modify a file, and reload the page in your browser to test it

by the way with the introduction of webpack i included the development server, the new NPM `start` script launch it. It reloads the browser for you every time a change to the source is made.

**Comment by cormier** [comment]
I have reviewed the PR. It has been a while since I have looked this closely at the code of the project. ☺

Thanks @yeiniel for submitting this PR. Here are my comments:

Regarding the MR in general: 
I like this MR because it tackles the underlying issue of updating some libraries (npm and travis) and ways of doing things (using only npm for dependencies instead of bower + npm).

Regarding packaging and the build step: 
This PR introduces a build step. GB was built with the idea that one should just be able to clone the repo and be able to start using it. As @yeiniel has mentionned, we can use the webpack development server autoreload feature to have a simple development workflow.

I am in favour of introducing a build step and believe that overall it would bring more benefits than problems.
- Our CSS is large and hard to maintain, and I believe that adding a build step would make the integration of a CSS preprocessor like Sass easier.
- We could also add a step to minify the JS and CSS
- For the users who do not want to build GB, we could provide a package. This package could be built by travis on every tag. 

If we all agree in introducing the build step, I believe we should modify the following before merging this PR:

- We have a two "improve unit testing" commits and one "try to fix test exec on travis env". Can we squash these and add more details on _how_ it improves unit testing?
- The underscore import is commented out in 330216b59cd1c3bace0e1890645dab97fddab172. Can we remove it instead ?
- The server has to be started with `npm start`. Can we update the readme to reflect this ?

**Comment by yeiniel** [comment]
i already made the suggested updates in case you all agree with merging the PR

**Comment by lorenzhs** [comment]
Thanks for reviewing this, @cormier! I like the idea of adding a CSS preprocessor etc. later. I’m good to merge this once your concerns are addressed.

**Comment by lorenzhs** [comment]
So are we good to merge this?

**Comment by cormier** [comment]
We are !

**Comment by lorenzhs** [comment]
Thanks again, @yeiniel! This is great.

**Pull request merged**
