### PR TITLE
Remove support for non-native emoji rendering

### PR DESCRIPTION
**Pull request by lorenzhs**
It's not 2014 anymore, every reasonable platform supports displaying emoji natively these days. Let's remove a filter that has ceased to provide value.

### CODE REVIEW

**Comment by lorenzhs** [comment]
Note that emojione is still used for text input of emoji (`:+1:` → :+1:) and thus not removed.

**Comment by AStove** [comment]
Great, I was concidering updating that but removing it is even better.

**Comment by AStove** [comment]
I think you forgot to remove the actual library from the index.hml

**Comment by lorenzhs** [comment]
Nope I didn't forget, see the first comment above. It's still used to convert text-input emoji into actual emoji.

**Comment by AStove** [comment]
Sorry I didn't read..

**Pull request merged**
