### PR TITLE
Fix unable to use history when input bar empty

### LINKED ISSUE #1130: Input history broken if nothing in input
It seems like the input history (arrow up) does't seem to work unless there's at least 1 character already in the input.

### PR DESCRIPTION
**Pull request by AStove**
Fixes #1130

### CODE REVIEW

**Comment by lorenzhs** [comment]
Hm is it intended that the cursor is in the first position when you scroll up from an empty line? I think it would be more natural if it was in the last position. I don't know whether that changed recently or not.

**Comment by AStove** [comment]
It does go to the last position for me. Or do you mean on multiline inputs?

**Comment by lorenzhs** [comment]
Nope it jumps to position 0 if I press the up arrow from an empty input bar. I'm using Firefox 76. Chrome works fine.

**Comment by AStove** [comment]
That should be better. I've looked online a bit and there doesn't seem to be a better way to do this. Also I've seen someone do 1ms so they must have had the same problem.

**Comment by lorenzhs** [comment]
Ugh. Thanks so much!

**Pull request merged**
