### PR TITLE
Feature: imgur button

### PR DESCRIPTION
**Pull request by lorenzhs**
99% of this is @Bakke's work. I cleaned up the history a bit and changed it to add the URL to the newly uploaded image into the input bar instead of sending it directly.

TODO: drag'n'drop should not send directly, use the insert-into-input-bar functionality there as well

### CODE REVIEW

**Comment by Bakke** [comment]
The Imgur-app is not whitelisted yet, so it is limited to1,250 uploads per day. I have submitted two requests to be white-listed (first one two or three weeks ago), but no answer.

**Comment by Bakke** [comment]
@lorenzhs your changes looks really good! Testet the latest version now :)

Using drag and drop is still sending images directly?

**Comment by lorenzhs** [comment]
Thanks! I didn't even look at the drag and drop code to be honest. I'll check it out and maybe factor out the insertion part into an `insertAtCaret` function. 

About the API, I generated a client ID myself now because @torvhe said you wanted to use an "official" one for GB. 1250 should be fine for now, we don't have *that* many users (I think, we don't really know). But you're right, we should get it whitelisted eventually.

**Comment by lorenzhs** [comment]
I changed the drag'n'drop behaviour to match the button, and also submitted a whitelisting request to imgur. Let's see if/when/how they respond.

**Comment by zakcrawford** [comment]
I'd say this is safe to merge, if you run into rate limit issues lemme know.

**Comment by lorenzhs** [comment]
@zakcrawford cool, do you know of a way to see current usage (X/1250)?

**Pull request merged**
