### PR TITLE
Add date change markers

### PR DESCRIPTION
**Pull request by lorenzhs**
This adds date change markers dynamically. Thanks for @pmelanson for getting my prototype up to speed.

I can kill the merge commit if you'd like but I don't think it hurts.

### CODE REVIEW

**Comment by torhve** [comment]
When all the lines are days old and there hasn't been any new messages, shouldn't the last line be a date change line?

**Comment by lorenzhs** [comment]
Hmm yes that would be a good idea to have. I guess this should go into `handleBufferLineAdded` and check whether the last message was sent today?

**Comment by torhve** [comment]
Will you add this before we merge, or wait til later? I think this is good to go as it is, but would like the feature I propose as now it can be a bit confusing, looking like messages are from today.

**Comment by pmelanson** [comment]
I have a bit of free time, @lorenzhs if you don't have time atm I could have a crack at it now that I know what function to start at.

**Comment by lorenzhs** [comment]
Please feel free to go ahead, @pmelanson! It's always nice to have new contributors, it's more fun that way and more people have more ideas.

**Comment by pmelanson** [comment]
Responding to IRC, for a different message than "Date changed to"

for a change of one day:
`Wednesday Nov 25, 2015` (full length week day, abbrev month, comma before year)

for a change of two days:
`Wednesday Nov 25, 2015 (266 days later)` or
`Wednesday Nov 25, 2015 (266 days earlier)`
(same as date1, but doesn't print what the previous date was)

Thoughts on these?

**Comment by torhve** [comment]
I like this as it is, and think it's good to merge. We can always change the wording later when we have a better feel for it after using it for a bit.

If @lorenzhs also approve of the wording I will merge this (or he can)

**Comment by lorenzhs** [comment]
I think this is good to go

**Pull request merged**
