### PR TITLE
Parse colours in buffer title

### LINKED ISSUE #308: Colours in buffer title (topic) don't render
Glowing Bear does not parse colour codes in the /topic.

Example:

### PR DESCRIPTION
**Pull request by lorenzhs**
Requires a WeeChat version including https://github.com/weechat/weechat/commit/013165209af818daba6b6c5869e822ec9cb86fc3, i.e., WeeChat 1.1 or a November 2014 nightly (or later). Ffor previous versions, see https://github.com/weechat/weechat/issues/237

Fixes #308

### CODE REVIEW

**Comment by lorenzhs** [comment]
WeeChat 1.1 was released which fixes the bug mentioned above, so we should be good to go on this. Any opinions?

**Comment by torhve** [comment]
Is there any side effects if you haven't upgraded?

**Comment by lorenzhs** [comment]
Since WeeChat sent IRC colour codes previously, and those don't collide with WeeChat colour codes, I don't expect any side effects. While I haven't tested, I'd be very surprised if something broke

**Comment by torhve** [comment]
I will test it and merge it

**Pull request merged**
