### PR TITLE
Add input field for WebSocket path, resolves #1008

### LINKED ISSUE #1008: Allow specifying custom websocket path
Currently, it seems to be [hard-coded](https://github.com/glowing-bear/glowing-bear/blob/84018d4bec3d17cd9edafcd55843054959b9d992/js/connection.js#L30).

### PR DESCRIPTION
**Pull request by rio-**

### CODE REVIEW

**Comment by brauner** [comment]
What's the state of this? That would be quite a useful feature!

**Comment by rio-** [comment]
@brauner See https://github.com/glowing-bear/glowing-bear/pull/1090

**Comment by brauner** [comment]
Sweet, can this here be closed then?

**Comment by rio-** [comment]
I guess so. I'll close it.

**Pull request closed without merging**
