### PR TITLE
update karma and install some dependencies; fixes #696

### LINKED ISSUE #696: npm install fails on Node.js 5.1.0, Mac OS X
I recently upgraded Node.js and `npm test` runs started throwing all sorts of errors afterwards. Apparently an old version of `fsevents` fails to build now and the npm dependency algorithm has somehow changed (I'm guessing optional dependencies aren't installed by default any more?).

Here's a log for reference. I'll send a PR.

```
 npm test

> glowing-bear@0.5.0 pretest /Users/dance/dev/glowing-bear
> npm install

npm WARN engine karma@0.10.10: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"5.1.0","npm":"3.3.12"})

> fsevents@0.2.1 install /Users/dance/dev/glowing-bear/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:348:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../../nan/nan.h:355:53: error: no member named 'New' in 'v8::String'; did you
      mean 'v8::TypeSwitch::New'?
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ^~~~~~~~~~~~~~~
                                                    v8::TypeSwitch::New
/Users/dance/.node-gyp/5.1.0/include/node/v8.h:4704:28: note:
      'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:355:69: error: calling a private constructor of class
      'v8::Local<v8::FunctionTemplate>'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                                    ^
/Users/dance/.node-gyp/5.1.0/include/node/v8.h:326:13: note: declared private
      here
  V8_INLINE Local(S* that)
            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:357:65: error: too few arguments to function call, expected 2,
      have 1
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                      ~~~~~~~~~~~~~~            ^
/Users/dance/.node-gyp/5.1.0/include/node/v8.h:2496:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
../../nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:373:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:381:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:406:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                      ^
../../nan/nan.h:416:12: error: no matching function for call to 'New'
    return node::Buffer::New(data, size);
           ^~~~~~~~~~~~~~~~~
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:28:40: note: candidate
      function not viable: no known conversion from 'char *' to 'v8::Isolate *'
      for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note: candidate
      function not viable: no known conversion from 'char *' to 'v8::Isolate *'
      for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note: candidate
      function not viable: requires 3 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:420:12: error: no matching function for call to 'New'
    return node::Buffer::New(size);
           ^~~~~~~~~~~~~~~~~
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:28:40: note: candidate
      function not viable: requires 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note: candidate
      function not viable: requires at least 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note: candidate
      function not viable: requires 3 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dance/.node-gyp/5.1.0/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:427:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:727:49: error: too few arguments to function call, single
      argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/dance/.node-gyp/5.1.0/include/node/v8.h:2930:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dance/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/dance/.nvm/versions/node/v5.1.0/bin/node" "/Users/dance/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dance/dev/glowing-bear/node_modules/fsevents
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:fsevents@0.2.1 fsevents@0.2.1 install: `node-gyp rebuild`
npm WARN install:fsevents@0.2.1 Exit status 1

> ws@0.4.32 install /Users/dance/dev/glowing-bear/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> glowing-bear@0.5.0 postinstall /Users/dance/dev/glowing-bear
> bower install

glowing-bear@0.5.0 /Users/dance/dev/glowing-bear
├─┬ bower@1.7.0
│ ├─┬ bower-config@1.3.0
│ │ └─┬ optimist@0.6.1
│ │   ├── minimist@0.0.10
│ │   └── wordwrap@0.0.3
│ ├─┬ bower-registry-client@1.0.0
│ │ └── async@0.2.10
│ ├─┬ decompress-zip@0.1.0
│ │ └─┬ readable-stream@1.1.13
│ │   ├── core-util-is@1.0.2
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├─┬ fstream@1.0.8
│ │ └── inherits@2.0.1
│ ├─┬ fstream-ignore@1.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@3.0.0
│ │   └─┬ brace-expansion@1.1.2
│ │     ├── balanced-match@0.3.0
│ │     └── concat-map@0.0.1
│ ├─┬ glob@4.5.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@2.0.10
│ │   └─┬ brace-expansion@1.1.2
│ │     ├── balanced-match@0.3.0
│ │     └── concat-map@0.0.1
│ ├─┬ handlebars@2.0.0
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ uglify-js@2.3.6
│ │   └── async@0.2.10
│ ├── lru-cache@2.7.3
│ ├─┬ p-throttler@0.1.1
│ │ └── q@0.9.7
│ ├─┬ request@2.53.0
│ │ └─┬ bl@0.9.4
│ │   └─┬ readable-stream@1.0.33
│ │     ├── core-util-is@1.0.2
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ rimraf@2.4.4
│ │ └─┬ glob@5.0.15
│ │   ├── inherits@2.0.1
│ │   └─┬ minimatch@3.0.0
│ │     └─┬ brace-expansion@1.1.2
│ │       ├── balanced-match@0.3.0
│ │       └── concat-map@0.0.1
│ ├─┬ tar-fs@1.8.1
│ │ └─┬ tar-stream@1.3.1
│ │   └─┬ readable-stream@2.0.4
│ │     ├── core-util-is@1.0.2
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ └─┬ update-notifier@0.3.2
│   └─┬ latest-version@1.0.1
│     └─┬ package-json@1.2.0
│       ├─┬ got@3.3.1
│       │ ├─┬ duplexify@3.4.2
│       │ │ └─┬ readable-stream@2.0.4
│       │ │   ├── core-util-is@1.0.2
│       │ │   ├── inherits@2.0.1
│       │ │   ├── isarray@0.0.1
│       │ │   └── string_decoder@0.10.31
│       │ ├─┬ nested-error-stacks@1.0.2
│       │ │ └── inherits@2.0.1
│       │ └─┬ read-all-stream@3.0.1
│       │   └─┬ readable-stream@2.0.4
│       │     ├── core-util-is@1.0.2
│       │     ├── inherits@2.0.1
│       │     ├── isarray@0.0.1
│       │     └── string_decoder@0.10.31
│       └─┬ registry-url@3.0.3
│         └─┬ rc@1.1.5
│           └── strip-json-comments@1.0.4
├─┬ http-server@0.6.1
│ ├── colors@0.6.2
│ ├─┬ ecstatic@0.4.13
│ │ ├── ent@0.0.7
│ │ └── optimist@0.3.7
│ ├── opener@1.3.0
│ ├─┬ optimist@0.5.2
│ │ └── wordwrap@0.0.3
│ ├─┬ portfinder@0.2.1
│ │ └── mkdirp@0.0.7
│ └─┬ union@0.3.8
│   ├── pkginfo@0.2.3
│   └── qs@0.5.6
├─┬ jshint@2.8.0
│ ├── cli@0.6.6
│ ├─┬ console-browserify@1.1.0
│ │ └── date-now@0.1.4
│ ├── exit@0.1.2
│ ├─┬ htmlparser2@3.8.3
│ │ ├── domelementtype@1.3.0
│ │ ├── domhandler@2.3.0
│ │ ├─┬ domutils@1.5.1
│ │ │ └─┬ dom-serializer@0.1.0
│ │ │   ├── domelementtype@1.1.3
│ │ │   └── entities@1.1.1
│ │ ├── entities@1.0.0
│ │ └─┬ readable-stream@1.1.13
│ │   ├── core-util-is@1.0.2
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── lodash@3.7.0
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── shelljs@0.3.0
│ └── strip-json-comments@1.0.4
├─┬ karma@0.10.10
│ ├─┬ chokidar@0.8.4
│ │ └── recursive-readdir@0.0.2
│ ├── coffee-script@1.6.3
│ ├── colors@0.6.0-1
│ ├─┬ connect@2.8.8
│ │ ├── buffer-crc32@0.2.1
│ │ ├── bytes@0.2.0
│ │ ├── cookie@0.1.0
│ │ ├── cookie-signature@1.0.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── formidable@1.0.14
│ │ ├── fresh@0.2.0
│ │ ├── methods@0.0.1
│ │ ├── pause@0.0.1
│ │ ├── qs@0.6.5
│ │ ├─┬ send@0.1.4
│ │ │ └── range-parser@0.0.4
│ │ └── uid2@0.0.2
│ ├── di@0.0.1
│ ├─┬ glob@3.1.21
│ │ └── inherits@1.0.2
│ ├── graceful-fs@1.2.3
│ ├─┬ http-proxy@0.10.4
│ │ ├── optimist@0.6.1
│ │ ├── pkginfo@0.3.1
│ │ └─┬ utile@0.2.1
│ │   ├── deep-equal@1.0.1
│ │   ├── i@0.3.3
│ │   └── ncp@0.4.2
│ ├── lodash@1.1.1
│ ├─┬ log4js@0.6.29
│ │ ├── readable-stream@1.0.33
│ │ ├── semver@4.3.6
│ │ └── underscore@1.8.2
│ ├── mime@1.2.11
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.7.3
│ │ └── sigmund@1.0.1
│ ├── optimist@0.3.7
│ ├── q@0.9.7
│ ├── rimraf@2.1.4
│ ├─┬ socket.io@0.9.17
│ │ ├── base64id@0.1.0
│ │ ├── policyfile@0.0.4
│ │ ├── redis@0.7.3
│ │ └─┬ socket.io-client@0.9.16
│ │   ├─┬ active-x-obfuscator@0.0.1
│ │   │ └── zeparser@0.0.5
│ │   ├── uglify-js@1.2.5
│ │   ├─┬ ws@0.4.32
│ │   │ ├── commander@2.1.0
│ │   │ ├── nan@1.0.0
│ │   │ ├── options@0.0.6
│ │   │ └── tinycolor@0.0.1
│ │   └── xmlhttprequest@1.4.2
│ └─┬ useragent@2.0.10
│   └── lru-cache@2.2.4
├── UNMET PEER DEPENDENCY karma-chrome-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-coffee-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-firefox-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-html2js-preprocessor@~0.1.0
├── UNMET PEER DEPENDENCY karma-jasmine@~0.1.0
├─┬ karma-junit-reporter@0.2.2
│ └── xmlbuilder@0.4.2
├── UNMET PEER DEPENDENCY karma-phantomjs-launcher@~0.1.0
├── UNMET PEER DEPENDENCY karma-requirejs@~0.2.0
├── UNMET PEER DEPENDENCY karma-script-launcher@~0.1.0
├─┬ protractor@0.20.1
│ ├── adm-zip@0.4.7
│ ├─┬ glob@3.2.11
│ │ ├── inherits@2.0.1
│ │ └── minimatch@0.3.0
│ ├── minijasminenode@1.1.1
│ ├─┬ optimist@0.6.1
│ │ └── minimist@0.0.10
│ ├── q@1.0.0
│ ├── saucelabs@0.1.1
│ └── selenium-webdriver@2.40.0
├── shelljs@0.2.6
└─┬ uglify-js@2.6.1
  ├── async@0.2.10
  ├── source-map@0.5.3
  ├── uglify-to-browserify@1.0.2
  └─┬ yargs@3.10.0
    ├── camelcase@1.2.1
    ├─┬ cliui@2.1.0
    │ ├─┬ center-align@0.1.2
    │ │ ├─┬ align-text@0.1.3
    │ │ │ ├─┬ kind-of@2.0.1
    │ │ │ │ └── is-buffer@1.1.0
    │ │ │ ├── longest@1.0.1
    │ │ │ └── repeat-string@1.5.2
    │ │ └── lazy-cache@0.2.4
    │ ├── right-align@0.1.3
    │ └── wordwrap@0.0.2
    ├── decamelize@1.1.1
    └── window-size@0.1.0

npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-jasmine@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-requirejs@~0.2.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-coffee-preprocessor@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-html2js-preprocessor@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-chrome-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-firefox-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-phantomjs-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-script-launcher@~0.1.0 but none was installed.

> glowing-bear@0.5.0 test /Users/dance/dev/glowing-bear
> karma start test/karma.conf.js

WARN [plugin]: Cannot find plugin "karma-phantomjs-launcher".
  Did you forget to install it ?
  npm install karma-phantomjs-launcher --save-dev
WARN [plugin]: Cannot find plugin "karma-jasmine".
  Did you forget to install it ?
  npm install karma-jasmine --save-dev
/Users/dance/dev/glowing-bear/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (/Users/dance/dev/glowing-bear/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/Users/dance/dev/glowing-bear/node_modules/di/lib/injector.js:9:13)
    at get (/Users/dance/dev/glowing-bear/node_modules/di/lib/injector.js:54:19)
    at /Users/dance/dev/glowing-bear/node_modules/karma/lib/server.js:28:14
    at Array.forEach (native)
    at start (/Users/dance/dev/glowing-bear/node_modules/karma/lib/server.js:27:21)
    at invoke (/Users/dance/dev/glowing-bear/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/Users/dance/dev/glowing-bear/node_modules/karma/lib/server.js:206:12)
    at Object.<anonymous> (/Users/dance/dev/glowing-bear/node_modules/karma/bin/karma:19:39)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.
```

### PR DESCRIPTION
**Pull request by dancek**

### CODE REVIEW

**Comment by lorenzhs** [comment]
Sorry if I'm misunderstanding something, but shouldn't npm pull in dependencies automatically? Or are we using something without explicitly listing it, which used to be pulled in as a dependency of something but isn't anymore?

**Comment by dancek** [comment]
I don't know how these dependencies were installed before, but they aren't being installed any more.

```
WARN [plugin]: Cannot find plugin "karma-phantomjs-launcher".
  Did you forget to install it ?
  npm install karma-phantomjs-launcher --save-dev
WARN [plugin]: Cannot find plugin "karma-jasmine".
  Did you forget to install it ?
  npm install karma-jasmine --save-dev
```
(from #696)

**Comment by dancek** [comment]
From https://github.com/npm/npm/issues/6565 it looks like `peerDependencies` were auto-installed before, but aren't in current versions of `npm`.

**Comment by dancek** [comment]
> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.
http://blog.npmjs.org/post/110924823920/npm-weekly-5

Reading the log in #696 more thoroughly, I realize there are even more dependencies that should be declared.

```
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-jasmine@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-requirejs@~0.2.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-coffee-preprocessor@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-html2js-preprocessor@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-chrome-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-firefox-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-phantomjs-launcher@~0.1.0 but none was installed.
npm WARN EPEERINVALID karma@0.10.10 requires a peer of karma-script-launcher@~0.1.0 but none was installed.
```

**Comment by dancek** [comment]
I'll take that back. In this branch, I'm not getting any `npm WARN EPEERINVALID` warnings.

**Comment by lorenzhs** [comment]
cool, thanks for looking this up!

**Pull request merged**
