### PR TITLE
Implement infinite scrolling

### PR DESCRIPTION
**Pull request by torhve**
I't not perfect but it's a start.

### CODE REVIEW

**Comment by lorenzhs** [comment]
I noticed that when switching to a previously not visited buffer (i.e. lines aren't cached) where the initial amount of lines doesn't suffice to fill the screen, it triggers a second fetch. Not sure if intended but pretty cool!

**Comment by torhve** [comment]
Not intentional, as long as the thingy is visible it will happen. But I guess it actually is a good thing?

**Comment by lorenzhs** [comment]
Yeah, I like it, and it only happens once so it won't keep going on forever if there was a giant netsplit and you're using a smart filter.

**Comment by torhve** [comment]
Been running this a few days and I like it. Maybe could merge and see if users finds any problem?

**Comment by lorenzhs** [comment]
yup I agree, it feels pretty nice overall

**Pull request merged**
