### PR TITLE
Shrink nav icons

### PR DESCRIPTION
**Pull request by stenehall**
* Shrink the nav icons and bear for a better mobile experience.
* Shrink the nav icons on desktop for a better navbar.

### CODE REVIEW

**Comment by lorenzhs** [comment]
I find them hard enough to hit already, so while I haven't tested your changes yet, are you sure this improves the experience?

**Comment by stenehall** [comment]
Ok, experience might have been the wrong word here. For a cleaner look, rather. If people actually find them hard to hit I'd suggest we keep the icons small but actually increase the hit area a little by adding some padding.

**Comment by torhve** [comment]
Agree with Lorenz here, they are too tiny now. But as you say, what about compromise, decrease the size a little but keep the hit area just as big. Then it will look nicer than now but experience will be the same.

**Comment by torhve** [comment]
Merging this for now, we can take a new look at the icon sizes and navbar height when we get scroll to hide.

**Comment by lorenzhs** [comment]
+1 for increasing them a bit again

**Pull request merged**
